
################### English Navigation ########################
[[main]]
name = "Home"
url = "#banner"
weight = 0


[[main]]
name = "About"
url = "#about"
weight = 1

# [[main]]
# name = "services"
# url = "#services"
# weight = 2

[[main]]
name = "Our Science"
url = "#our-science"
weight = 2

[[main]]
name = "Team"
url = "#team"
weight = 3

# [[main]]
# name = "pricing"
# url = "#pricing"
# weight = 5

[[main]]
name = "Blog"
url = "#blog"
weight = 4

[[main]]
name = "Contact"
url = "#contact"
weight = 5


############## Example how to create a dropdown menu
# [[main]]
# name = "Dropdown"
# weight = 6
# hasChildren = true
# 
# [[main]]
# parent = "Dropdown"
# name = "Dropdown 1"
# url = "#"
# weight = 1
# 
# [[main]]
# parent = "Dropdown"
# name = "Dropdown 2"
# url = "#"
# weight = 2



############## Example linking to other sites
# [[main]]
# name = "themefisher"
# url = "https://themefisher.com/"
# weight = 8

